spring:
  application:
    name: patientService
  datasource:
    password: Assur@3260
    url: jdbc:mysql://localhost:3306/patient_service
    username: root

  jpa:
    hibernate:
      ddl-auto: update

   #swagger path api ui representation
      #server/v3/api-docs      
   